# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.streaming_device_data import StreamingDeviceData  # noqa: F401,E501
from swagger_server import util


class RequestUpdateStreamingDevice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, external_transaction_id: str=None, data: StreamingDeviceData=None):  # noqa: E501
        """RequestUpdateStreamingDevice - a model defined in Swagger

        :param channel: The channel of this RequestUpdateStreamingDevice.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestUpdateStreamingDevice.  # noqa: E501
        :type external_transaction_id: str
        :param data: The data of this RequestUpdateStreamingDevice.  # noqa: E501
        :type data: StreamingDeviceData
        """
        self.swagger_types = {
            'channel': str,
            'external_transaction_id': str,
            'data': StreamingDeviceData
        }

        self.attribute_map = {
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId',
            'data': 'data'
        }
        self._channel = channel
        self._external_transaction_id = external_transaction_id
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'RequestUpdateStreamingDevice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestUpdateStreaming_Device of this RequestUpdateStreamingDevice.  # noqa: E501
        :rtype: RequestUpdateStreamingDevice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestUpdateStreamingDevice.


        :return: The channel of this RequestUpdateStreamingDevice.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestUpdateStreamingDevice.


        :param channel: The channel of this RequestUpdateStreamingDevice.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestUpdateStreamingDevice.


        :return: The external_transaction_id of this RequestUpdateStreamingDevice.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestUpdateStreamingDevice.


        :param external_transaction_id: The external_transaction_id of this RequestUpdateStreamingDevice.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id

    @property
    def data(self) -> StreamingDeviceData:
        """Gets the data of this RequestUpdateStreamingDevice.


        :return: The data of this RequestUpdateStreamingDevice.
        :rtype: StreamingDeviceData
        """
        return self._data

    @data.setter
    def data(self, data: StreamingDeviceData):
        """Sets the data of this RequestUpdateStreamingDevice.


        :param data: The data of this RequestUpdateStreamingDevice.
        :type data: StreamingDeviceData
        """

        self._data = data
