# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StreamingDeviceData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_streaming_device: int=None, name_streaming_device: str=None, state_streaming_device: bool=None, created_at: datetime=None):  # noqa: E501
        """StreamingDeviceData - a model defined in Swagger

        :param id_streaming_device: The id_streaming_device of this StreamingDeviceData.  # noqa: E501
        :type id_streaming_device: int
        :param name_streaming_device: The name_streaming_device of this StreamingDeviceData.  # noqa: E501
        :type name_streaming_device: str
        :param state_streaming_device: The state_streaming_device of this StreamingDeviceData.  # noqa: E501
        :type state_streaming_device: bool
        :param created_at: The created_at of this StreamingDeviceData.  # noqa: E501
        :type created_at: datetime
        """
        self.swagger_types = {
            'id_streaming_device': int,
            'name_streaming_device': str,
            'state_streaming_device': bool,
            'created_at': datetime
        }

        self.attribute_map = {
            'id_streaming_device': 'id_streaming_device',
            'name_streaming_device': 'name_streaming_device',
            'state_streaming_device': 'state_streaming_device',
            'created_at': 'created_at'
        }
        self._id_streaming_device = id_streaming_device
        self._name_streaming_device = name_streaming_device
        self._state_streaming_device = state_streaming_device
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt) -> 'StreamingDeviceData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Streaming_DeviceData of this StreamingDeviceData.  # noqa: E501
        :rtype: StreamingDeviceData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_streaming_device(self) -> int:
        """Gets the id_streaming_device of this StreamingDeviceData.


        :return: The id_streaming_device of this StreamingDeviceData.
        :rtype: int
        """
        return self._id_streaming_device

    @id_streaming_device.setter
    def id_streaming_device(self, id_streaming_device: int):
        """Sets the id_streaming_device of this StreamingDeviceData.


        :param id_streaming_device: The id_streaming_device of this StreamingDeviceData.
        :type id_streaming_device: int
        """

        self._id_streaming_device = id_streaming_device

    @property
    def name_streaming_device(self) -> str:
        """Gets the name_streaming_device of this StreamingDeviceData.


        :return: The name_streaming_device of this StreamingDeviceData.
        :rtype: str
        """
        return self._name_streaming_device

    @name_streaming_device.setter
    def name_streaming_device(self, name_streaming_device: str):
        """Sets the name_streaming_device of this StreamingDeviceData.


        :param name_streaming_device: The name_streaming_device of this StreamingDeviceData.
        :type name_streaming_device: str
        """

        self._name_streaming_device = name_streaming_device

    @property
    def state_streaming_device(self) -> bool:
        """Gets the state_streaming_device of this StreamingDeviceData.


        :return: The state_streaming_device of this StreamingDeviceData.
        :rtype: bool
        """
        return self._state_streaming_device

    @state_streaming_device.setter
    def state_streaming_device(self, state_streaming_device: bool):
        """Sets the state_streaming_device of this StreamingDeviceData.


        :param state_streaming_device: The state_streaming_device of this StreamingDeviceData.
        :type state_streaming_device: bool
        """

        self._state_streaming_device = state_streaming_device

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this StreamingDeviceData.


        :return: The created_at of this StreamingDeviceData.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this StreamingDeviceData.


        :param created_at: The created_at of this StreamingDeviceData.
        :type created_at: datetime
        """

        self._created_at = created_at
